Doc: Getting started update
surrealdb/www.surrealdb.com pull request #156
Opened 2023-06-05 01:02 UTC by Ekwuno

This PR updates the quick start page and also introduces some restructure in the nav bar

2023-06-05 02:35 UTC, Ekwuno commented
Going to do one final sweep before review.

2023-06-05 07:03 UTC, kearfy requested changes

2023-06-05 07:03 UTC, kearfy commented on app/templates/docs/introduction/start.hbs
> +	<h3>Querying data with SELECT</h3>
```suggestion
	<h3>Querying data with <code>SELECT</code></h3>
```

2023-06-05 07:03 UTC, kearfy commented on app/templates/docs/introduction/start.hbs
> +	retrieve data from both the 'article' and the 'account' table in one query.</p>
```suggestion
	retrieve data from both the <code>article</code> and the <code>account</code> table in one query.</p>
```

2023-06-05 07:03 UTC, kearfy commented on app/templates/docs/introduction/start.hbs
> +	<p> You can also delete specific records DELETE person:david. You could also delete a record with specific conditions:</p>
```suggestion
	<h3><code>DELETE</code></h3>
	<p> You can also delete specific records with a query like: <code>DELETE person:david</code>. You could also delete a record with specific conditions:</p>
```

2023-06-05 07:03 UTC, kearfy commented on app/templates/docs/introduction/start.hbs
> +	<p> Similar to UPDATE in SQL you can also update specific IDs, for example say you wanted to update the first name of the
```suggestion
	<h3><code>UPDATE</code></h3>
	<p> Similar to <code>UPDATE</code> in SQL you can also update specific IDs, for example say you wanted to update the first name of the
```

2023-06-05 07:36 UTC, Ekwuno commented
@kearfy this PR is still a draft so most of this isn't ready for review and is updated in local already.

2023-06-05 15:35 UTC, Ekwuno commented
@kearfy thanks for the suggestions😁, I added them to this new update.

2023-06-05 17:28 UTC, AlexFrid reviewed
Have some comments here, will finish review tomorrow

2023-06-05 17:28 UTC, AlexFrid commented on app/snippets/docs/start/index/step10.surql
> +UPDATE age = 29 SET admin = false WHERE name.last = 'Adams';
This would not run as `age = 29` is not a table

2023-06-05 17:28 UTC, AlexFrid commented on app/snippets/docs/surrealql/statements/relate/simple.surql
> +-- This command creates a relationship ("edge") between all users from 'surrealdb' and all users who are developers.
This is actually wrong, this wouldn't even run.

You can do it using record ids, but it would only connect 1 at a time, not all the users.
You would currently need to loop through it

2023-06-05 19:49 UTC, kearfy commented on app/snippets/docs/surrealql/statements/relate/simple.surql
> +-- This command creates a relationship ("edge") between all users from 'surrealdb' and all users who are developers.
Oh interesting. Behaviour like this should be possible....

2023-06-05 23:12 UTC, Ekwuno commented on app/templates/docs/introduction/start.hbs
> -	<Code @name="docs/start/index/windows.shell" />
Windows is removed as well. Replaced with new commands.  <img width="953" alt="Screenshot 2023-06-05 at 22 35 46" src="https://github.com/surrealdb/www.surrealdb.com/assets/35943047/f1e1eb56-5d30-48ed-912b-6062f7421034">

2023-06-05 23:35 UTC, Ekwuno commented on app/templates/docs/introduction/start.hbs
> +	<p>First ensure that your database is setup correctly, run:</p>
Not exactly, the document should be as straight forward. So we have removed this installation step but add a note so it's clear its a prerequisite. 
<img width="966" alt="Screenshot 2023-06-06 at 00 35 12" src="https://github.com/surrealdb/www.surrealdb.com/assets/35943047/0bfa86cb-9cc4-49ed-9c23-753b72fe386a">

2023-06-05 23:44 UTC, Ekwuno commented on app/templates/docs/introduction/start.hbs
> +		<li><code>memory</code>: This argument likely indicates that the database should be run in memory. Databases run in memory can have
Sure I can update that. 🙂

2023-06-06 00:54 UTC, Ekwuno commented on app/templates/docs/introduction/start.hbs
> +		<li><code>memory</code>: This argument likely indicates that the database should be run in memory. Databases run in memory can have
Done

2023-06-06 09:03 UTC, Ekwuno commented on app/snippets/docs/start/index/step10.surql
> +UPDATE age = 29 SET admin = false WHERE name.last = 'Adams';
Updated this as well.

2023-06-06 10:06 UTC, AlexFrid commented on app/snippets/docs/surrealql/statements/relate/simple.surql
> +-- This command creates a relationship ("edge") between all users from 'surrealdb' and all users who are developers.
Yeah, it would be great if we could make it possible, would need some careful thought though as the looping could get really slow if you are relating each record between million/billion record tables. So it should be a active choice, rather than something that happens automatically, perhaps a different statement like `RELATE_ALL`🤔

2023-06-06 10:44 UTC, AlexFrid commented on app/templates/docs/introduction/start.hbs
> -	<Code @name="docs/start/index/windows.shell" />
Need to make sure we have both
![Uploading image.png…]()

2023-06-06 13:04 UTC, AlexFrid commented on app/snippets/docs/surrealql/statements/relate/simple.surql
> +-- This command creates a relationship ("edge") between all users from 'surrealdb' and all users who are developers.
We'll update the page with examples in another PR

2023-06-06 13:08 UTC, AlexFrid commented on app/templates/docs/surrealdb/index.hbs
> +	<p>Congratulations, you’re now on your way to database and API simplicity! For the next steps, take a look at some
Why is this here?

2023-06-06 15:49 UTC, kearfy requested changes

2023-06-06 15:49 UTC, kearfy commented on app/templates/docs/surrealdb/index.hbs
> +	<p>For the next steps, take a look at our <Link @link="docs.introduction.start"> getting started guide </Link> to see some of these functionalities in action.</p>
```suggestion
	<p>For the next steps, take a look at our <Link @link="docs.introduction.start"> introduction guide </Link> to see some of these functionalities in action.</p>
```

2023-06-06 15:49 UTC, kearfy commented on app/templates/docs/introduction/start.hbs
> +	</blockquote>
```suggestion
	<blockquote Green text="Note"> Surrealist is a third-party web-based SurrealQL client that allows you to run queries against your SurrealDB built and maintained
		<Link @link="https://github.com/StarlaneStudios">by StarlaneStudios</Link>!
	</blockquote>
```

2023-06-06 16:08 UTC, merged