Update the select statement page
surrealdb/www.surrealdb.com pull request #174
Opened 2023-06-16 17:20 UTC by AlexFrid

Added several updates to the select page
- Headings for better skim through
- More comments
- More and updated examples
- Documenting new features that were not documented before
- Adding links to relevant pages

2023-06-16 19:18 UTC, kearfy requested changes

2023-06-16 19:18 UTC, kearfy commented on app/templates/docs/surrealql/statements/select.hbs
> +	<Code @name="docs/surrealql/statements/select/syntax.typescript" text="Surql Syntax" />
```suggestion
	<Code @name="docs/surrealql/statements/select/syntax.typescript" text="SurrealQL Syntax" />
```

2023-06-16 19:18 UTC, kearfy commented on app/templates/docs/surrealql/statements/select.hbs
>  	<Code @name="docs/surrealql/statements/select/expr.surql" />
Just thinking about this, but is the select statement documentation page actually the correct place to explain expressions?

2023-06-19 08:35 UTC, AlexFrid commented on app/snippets/docs/surrealql/statements/select/syntax.typescript
> +SELECT [ VALUE ] @field [ AS @alias ]
Sure, updated the syntax to show show `fields` instead of `field` where applicable.

2023-06-19 08:38 UTC, AlexFrid commented on app/snippets/docs/surrealql/statements/select/expr.surql
> +SELECT * FROM person WHERE ->(reaction WHERE type='celebrate')->post;
sure

2023-06-19 08:40 UTC, AlexFrid commented on app/snippets/docs/surrealql/statements/select/expr.surql
> +SELECT * from $history;
I don't want to include the `RETURN` word here, I think it would just confuse people.

2023-06-19 08:44 UTC, AlexFrid commented on app/templates/docs/surrealql/statements/select.hbs
> +	<Code @name="docs/surrealql/statements/select/syntax.typescript" text="Surql Syntax" />
Why not Surql?
Isn't that the shorthand way to write SurrealQL?

2023-06-19 08:47 UTC, AlexFrid commented on app/templates/docs/surrealql/statements/select.hbs
>  	<Code @name="docs/surrealql/statements/select/expr.surql" />
I would say it's currently the best page as expressions are used in select statements. We change it later if we find a better place for it, but I don't think that finding a potentially better place should be a blocker for this PR.

2023-06-19 08:49 UTC, AlexFrid commented on app/snippets/docs/surrealql/statements/select/expr.surql
> +SELECT * from $history;
Unless we want to add a section that is the same in the `select` and `return` docs, which explains the differences?

2023-06-19 11:15 UTC, kearfy commented on app/snippets/docs/surrealql/statements/select/expr.surql
> +SELECT ->like->friend.name AS friends FROM person:tobie;
@AlexFrid bump? This conversation is hidden by github due to the amount of requests for changes 😛

2023-06-19 11:16 UTC, kearfy commented on app/templates/docs/surrealql/statements/select.hbs
> +	<Code @name="docs/surrealql/statements/select/syntax.typescript" text="Surql Syntax" />
I personally don't see the need to use a shortened name here, but if you want to then it's fine by me

2023-06-19 11:22 UTC, AlexFrid commented on app/snippets/docs/surrealql/statements/select/expr.surql
> +SELECT * from $history;
That's a fair point. I think we can have a separate PR once we have put more thought into where to explain expressions if we want to duplicate content or have a central place. For now, I don't see a reason to take it out from here.

2023-06-19 11:23 UTC, kearfy commented on app/snippets/docs/surrealql/statements/select/expr.surql
> +SELECT * from $history;
Sure! Makes sense

2023-06-19 11:29 UTC, kearfy commented on app/snippets/docs/surrealql/statements/select/expr.surql
> +SELECT ->like->friend.name AS friends FROM person:tobie;
Idiomatic is not perse singular right?

2023-06-20 09:45 UTC, AlexFrid commented on app/snippets/docs/surrealql/statements/select/expr.surql
> +SELECT ->like->friend.name AS friends FROM person:tobie;
lets change it to prioritise readability 👍

2023-06-20 09:49 UTC, kearfy approved these changes

2023-06-20 09:50 UTC, merged