Add list of reserved variable names
surrealdb/www.surrealdb.com pull request #176
Opened 2023-06-18 10:52 UTC by Odonno

I have included the list of reserved variable names as this is a common question.

1. I have added this list to the `parameters` page. It may not be the best place for it. What do you think?
2. I have only listed the variables I know. It may not be exhaustive. Are there any other variable names that I should know?

2023-06-19 11:13 UTC, kearfy requested changes

2023-06-19 11:13 UTC, kearfy commented on app/templates/docs/surrealql/parameters.hbs
> +					<td>Used for authentication</td>
```suggestion
					<td>Represents values from the <Link @link="docs.surrealql.functions.session">session</Link> functions as an object</td>
```

2023-06-19 11:13 UTC, kearfy commented on app/templates/docs/surrealql/parameters.hbs
> +					<td>Used for authentication</td>
```suggestion
					<td>Represents values held inside the JWT token used for the current session</td>
```

2023-06-19 11:13 UTC, kearfy commented on app/templates/docs/surrealql/parameters.hbs
> +				</tr>
```suggestion
				<tr>
					<td>
						<code>$before</code>
					</td>
					<td>Represents the value before a mutation on a field</td>
				</tr>
				<tr>
					<td>
						<code>$after</code>
					</td>
					<td>Represents the value after a mutation on a field</td>
				</tr>
				<tr>
					<td>
						<code>$value</code>
					</td>
					<td>Represents the value after a mutation on a field (identical to <code>$value</code></td>
				</tr>
```

2023-06-19 11:13 UTC, kearfy commented on app/templates/docs/surrealql/parameters.hbs
> +			</tbody>
```suggestion
				<tr>
					<td>
						<code>$parent</code>
					</td>
					<td>Represents the parent record in a subquery</td>
				</tr>
			</tbody>
```

2023-06-19 11:13 UTC, kearfy commented on app/templates/docs/surrealql/parameters.hbs
> +			<tbody>
```suggestion
			<tbody>
				<tr>
					<td>
						<code>$auth</code>
					</td>
					<td>Represents the currently authenticated scope user</td>
				</tr>
```

2023-06-19 12:24 UTC, Odonno commented on app/templates/docs/surrealql/parameters.hbs
> +				</tr>
`$value` identical to `$value`? Are you sure? :)

So I assume you meant `$after`?

2023-06-19 12:25 UTC, kearfy commented on app/templates/docs/surrealql/parameters.hbs
> +				</tr>
Yes! My bad 🤪

2023-06-19 12:26 UTC, kearfy commented on app/templates/docs/surrealql/parameters.hbs
> +				</tr>
I will make some new suggestions, one second

2023-06-19 12:26 UTC, Odonno commented
I was thinking about developer usage. I suppose `$before`, `$after` and `$value` are only used for `DEFINE` statement. I don't know if it throws an error on another statements like `SELECT`. 

If it does not throw error, I was thinking about adding a `context` column to know where we cannot use those variables.

2023-06-19 20:53 UTC, Odonno commented
Also add type for each variable.

2023-06-20 05:10 UTC, kearfy commented on app/templates/docs/surrealql/parameters.hbs
> +				</tr>
```suggestion
				<tr>
					<td>
						<code>$before</code>
					</td>
					<td>Represents the value before a mutation on a field</td>
				</tr>
				<tr>
					<td>
						<code>$after</code>
					</td>
					<td>Represents the value after a mutation on a field</td>
				</tr>
				<tr>
					<td>
						<code>$value</code>
					</td>
					<td>Represents the value after a mutation on a field (identical to <code>$after</code> in the case of an event)</td>
				</tr>
				<tr>
					<td>
						<code>$input</code>
					</td>
					<td>Represents the initially inputted value in a field definition, as the <code>value</code> clause could have modified the <code>$value</code> variable</td>
				</tr>				
```

2023-06-20 05:14 UTC, kearfy approved these changes

2023-06-20 05:14 UTC, merged