Docs: Add .env instruction for critical secure
surrealdb/www.surrealdb.com pull request #200
Opened 2023-07-04 10:53 UTC by miguelgargallo

Docs: Add .env instruction for critical secure

2023-07-05 15:52 UTC, Ekwuno requested changes
Thanks for sending in this PR. I have just done a first review.

2023-07-05 15:52 UTC, Ekwuno commented on app/templates/docs/integration/sdks/nodejs.hbs
> +	<p>First install dotenv:</p>
```suggestion
	<p> To do so, first install <Link @link="https://www.npmjs.com/package/dotenv">dotenv</Link>  which is an NPM package that loads environment variables from a  <code> .env </code> file</p>
```

2023-07-05 15:52 UTC, Ekwuno commented on app/templates/docs/integration/sdks/nodejs.hbs
> +	<p>Add a<code>.env</code>file:</p>
```suggestion
	<p>Add a <code>.env</code> file to the root of your project. Then input your SurrealDB credentials</p>
```

2023-07-05 15:52 UTC, Ekwuno commented on app/templates/docs/integration/sdks/nodejs.hbs
> +	<p>Then you use it as follows:</p>
```suggestion
	<p>Then in your `app.js` file  edit the values as follows:</p>
```

2023-07-05 15:52 UTC, Ekwuno commented on app/templates/docs/integration/sdks/nodejs.hbs
> +		SURREALDB_LINK=https://cloud.surrealdb.com/rpc
```suggestion
		SURREALDB_LINK=http://127.0.0.1:8000/rpc
```

2023-07-05 15:52 UTC, Ekwuno commented on app/templates/docs/integration/sdks/nodejs.hbs
> +		const db = new Surreal(surrealdblink); // Connect to SurrealDB but on your .env file
```suggestion
		const db = new Surreal(surrealdburl); // Connect to SurrealDB 
```

2023-07-05 20:55 UTC, Ekwuno commented
@miguelgargallo will you add the suggestions in this PR? I see you have marked them as resolved but it's not been added to the PR.

2023-07-05 20:56 UTC, Ekwuno commented
The same changes apply to #203 as well.

2023-07-06 07:29 UTC, miguelgargallo commented
changes will be applied in #203 in a while! 💜

2023-07-07 08:08 UTC, miguelgargallo commented
> @miguelgargallo will you add the suggestions to another commit for this PR? I see you have marked them as resolved but it's not been added to the PR.

applying to this right now, my apologies

2023-07-07 08:18 UTC, miguelgargallo commented
- [x] done

2023-07-10 14:05 UTC, Ekwuno commented on app/templates/docs/integration/sdks/nodejs.hbs
> +		SURREALDB_LINK=http://127.0.0.1:8000/rpc
```suggestion
		SURREALDB_URL=http://127.0.0.1:8000/rpc
```

2023-09-01 17:18 UTC, kearfy commented
Hi @miguelgargallo, copying over my response from #203 here!

I have taken a look at your suggested change but decided that we will not be merging this. While it absolutely is good practice to maintain connection details and similar in environment variables, it is an opinionated solution. We want to keep the documentation for SurrealDB and it's SDKs as abstract as possible, and don't feel like this is in line with that goal.

In any case, thanks for your contribution! It is much appreciated!

2023-09-01 17:18 UTC, closed without merging

2023-09-01 17:54 UTC, miguelgargallo commented
It's nothing you are welcome, see you at SurrealDB World 🥰🚀👩‍🚀🌠